### PR TITLE
Adjust alltoall count

### PR DESCRIPTION
**Pull request by lappazos**
Adjust torch-ucc alltoall according to UCC API change

### CODE REVIEW

**Comment by jladd-mlnx** [comment]
@srinivas212  
 @lappazos is an Nvidia employee reporting to me, and as such is covered under Nvidia CLA.

**Comment by srinivas212** [comment]
> @srinivas212
> @lappazos is an Nvidia employee reporting to me, and as such is covered under Nvidia CLA.

Hi @jladd-mlnx - let me check the issue. NVIDIA has already signed CLA - so all NVIDIA employees should be automatically covered.

**Comment by kingchc** [comment]
@lappazos - for the record, could you provide more info/pointer about the UCC API change? I assume you're referring to https://github.com/openucx/ucc/pull/259, correct?

**Comment by lappazos** [comment]
> @lappazos - for the record, could you provide more info/pointer about the UCC API change? I assume you're referring to [openucx/ucc#259](https://github.com/openucx/ucc/pull/259), correct?

The official API Change was in https://github.com/openucx/ucc/pull/225, PR 259 is the internal change in UCC that supports it

**Comment by lappazos** [comment]
@srinivas212 @kingchc can you please reboot the checks?

**Comment by lappazos** [comment]
@Sergei-Lebedev please review

**Comment by lappazos** [comment]
Tests are failing because https://github.com/openucx/ucc/pull/259 hasn't been merged yet.

**Comment by lappazos** [comment]
@srinivas212 @kingchc please approve tests to run

**Comment by kingchc** [comment]
Looks good to me. 

It looks like CI tests are failing due to UCX and not directly related to this PR, will investigate it in separate PR (e.g., see tests in #27)

**Pull request closed without merging**
