### PR TITLE
Add datatype BFloat16

### PR DESCRIPTION
**Pull request by lappazos**
Add support to datatype BFloat16

### CODE REVIEW

**Comment by lappazos** [comment]
UCC implementation will be merged soon in https://github.com/openucx/ucc/pull/333

**Comment by lappazos** [comment]
@kingchc please review, thanks

**Comment by kingchc** [comment]
@lappazos - thanks for adding the support. LGTM. Approved the workflow, will merge this once https://github.com/openucx/ucc/pull/333 is merged and all tests passes.

**Comment by lappazos** [comment]
@kingchc openucx/ucc#333 was merged - please test & merge this PR as well, thx

**Review by kingchc — APPROVED** [review]

**Pull request closed without merging**
